package constants

const (
	AnnotationPrefix            = "authproxy.stakater.com/"
	EnabledAnnotation           = "authproxy.stakater.com/enabled"
	SourceServiceNameAnnotation = "authproxy.stakater.com/source-service-name"
	ImageNameAnnotation         = "authproxy.stakater.com/image-name"
	ImageTagAnnotation          = "authproxy.stakater.com/image-tag"
	ImagePullPolicyAnnotation   = "authproxy.stakater.com/image-pull-policy"
)

var KeycloakArgs = []string{
	"listen",
	"listen-http",
	"discovery-url",
	"client-id",
	"client-secret",
	"redirection-url",
	"revocation-url",
	"skip-openid-provider-tls-verify",
	"openid-provider-proxy",
	"openid-provider-timeout",
	"base-uri",
	"oauth-uri",
	"scopes",
	"upstream-url",
	"upstream-ca",
	"resources",
	"headers",
	"preserve-host",
	"request-id-header",
	"response-headers",
	"enable-self-signed-tls",
	"self-signed-tls-hostnames",
	"self-signed-tls-expiration",
	"enable-request-id",
	"enable-logout-redirect",
	"enable-default-deny",
	"enable-encrypted-token",
	"enable-logging",
	"enable-json-logging",
	"enable-forwarding",
	"enable-security-filter",
	"enable-refresh-tokens",
	"enable-session-cookies",
	"enable-login-handler",
	"enable-token-header",
	"enable-authorization-header",
	"enable-authorization-cookies",
	"enable-https-redirection",
	"enable-profiling",
	"enable-metrics",
	"filter-browser-xss",
	"filter-content-nosniff",
	"filter-frame-deny",
	"content-security-policy",
	"localhost-metrics",
	"access-token-duration",
	"cookie-domain",
	"cookie-access-name",
	"cookie-refresh-name",
	"secure-cookie",
	"http-only-cookie",
	"match-claims",
	"add-claims",
	"tls-cert",
	"tls-private-key",
	"tls-ca-certificate",
	"tls-ca-key",
	"tls-client-certificate",
	"skip-upstream-tls-verify",
	"skip-client-id",
	"cors-origins",
	"cors-methods",
	"cors-headers",
	"cors-exposed-headers",
	"cors-credentials",
	"cors-max-age",
	"hostnames",
	"store-url",
	"encryption-key",
	"invalid-auth-redirects-with-303",
	"no-redirects",
	"skip-token-verification",
	"upstream-keepalives",
	"upstream-timeout",
	"upstream-keepalive-timeout",
	"upstream-tls-handshake-timeout",
	"upstream-response-header-timeout",
	"upstream-expect-continue-timeout",
	"verbose",
	"max-idle-connections",
	"max-idle-connections-per-host",
	"enabled-proxy-protocol",
	"server-read-timeout",
	"server-write-timeout",
	"server-idle-timeout",
	"use-letsencrypt",
	"letsencrypt-cache-dir",
	"sign-in-page",
	"forbidden-page",
	"tags",
	"forwarding-username",
	"forwarding-password",
	"forwarding-domains",
	"disable-all-logging",
}
