apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}
---
{{- if .Values.proxyinjector.watchGlobally }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels: 
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels: 
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "proxyinjector-name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "proxyinjector-name" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  labels: 
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
      - "extensions"
      - "apps"
    resources:
      - deployments
      - daemonsets
      - statefulsets
    verbs:
      - list
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  labels: 
{{ include "proxyinjector-labels.stakater" . | indent 4 }}
{{ include "proxyinjector-labels.chart" . | indent 4 }}
  name: {{ template "proxyinjector-name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "proxyinjector-name" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ template "proxyinjector-name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}